travis:
  secure:
    BINSTAR_TOKEN: n4cT5z6Pvp8GR0AoEHe0hvCybdlwgubv7RTYKa7xHrOorLtUuzEyNIYKhxGi2ujYQ2pmhVhwIzCB7j8Ju3gh2a9UdpkvSY1UM55G7gld6UIEyb1Oq+A41Q2vP5Wn0u7ZxPM7QzFTghFV9xNqpmxfuiKiSa9/ek4wyZUHVV+jLXrOeYizqdbogPLghCTkanYgvRUwWsHx8AsKhILeFcD0CKQhAprV+/Xyb5TAlmv/p4V7d2Yh70ptIJtalaBcKeg20BgJWsMTRBep0gxL5FZ0grkskiS85pSzJlk6Lzm/m+6y7VXQWx8FdH0RuuhxeZWPUrPP+G0nuUYJOBZQGww+1EsLdZxi8OsnEHBNy9PxNeiBFb25YclSvUp1yGxQ//ZrZVAByGxsS71SOG2mtGtLNBFi8VPr3ZmY6AwDu2B19V8zHdrAW+zlECQY3kKEKE4OC2R/SllJzVEv7FhsZD8WwZ3xQD2TgFJGmyqLyK2wy9XCVv7VDpgM0FlYE/YQTHpye9WdJR83/C6HCHhtA/BKLfdEBZ40J3FZecggbKZF1Gvz0q5e6jP15v+l1ctE5QBl4z3tby99HLgAFCEDMl7muusmfn3rGPkhODa0tUFRHlPjoXpv2ydPP/rFicsPmYdSiafE/jdQIlwxsAGM0qo1K8vPD5LG5P8+nZaM09Su2EU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
